table 'IPCA Mensal por Setor'
	lineageTag: 80740a3c-be22-4ad0-95cf-ec35ade25d61

	column 'Gp IPCA'
		dataType: string
		lineageTag: 72c125de-0710-4076-bd9a-239ffd67934a
		summarizeBy: none
		sourceColumn: Gp IPCA

		annotation SummarizationSetBy = Automatic

	column 'Data IPCA Gp'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 84f29e6a-2ab6-42c0-9e63-e58331c5e75d
		summarizeBy: none
		sourceColumn: Data IPCA Gp

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Valor IPCA Gp'
		dataType: double
		formatString: 0.00
		lineageTag: d2b85517-142f-4f75-8b1f-77b3fc6e912e
		summarizeBy: average
		sourceColumn: Valor IPCA Gp

		annotation SummarizationSetBy = User

	partition 'IPCA Mensal por Setor' = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("https://servicodados.ibge.gov.br/api/v3/agregados/7060/variaveis/63?classificacao=315[all]&view=flat&localidades=BR")),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"NC", "NN", "MC", "MN", "V", "D1C", "D1N", "D2C", "D2N", "D3C", "D3N", "D4C", "D4N"}, {"NC", "NN", "MC", "MN", "V", "D1C", "D1N", "D2C", "D2N", "D3C", "D3N", "D4C", "D4N"}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Expanded Column1", [PromoteAllScalars=true]),
				    #"Removed Other Columns" = Table.SelectColumns(#"Promoted Headers",{"Geral, grupo, subgrupo, item e subitem", "Mês", "Valor"}),
				    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Removed Other Columns", {{"Geral, grupo, subgrupo, item e subitem", each Text.AfterDelimiter(_, "."), type text}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Extracted Text After Delimiter",{{"Geral, grupo, subgrupo, item e subitem", type text}, {"Mês", type date}, {"Valor", type number}}),
				    #"Rounded Off" = Table.TransformColumns(#"Changed Type",{{"Valor", each Number.Round(_, 2), type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Rounded Off",{{"Mês", "Data IPCA Gp"}, {"Valor", "Valor IPCA Gp"}, {"Geral, grupo, subgrupo, item e subitem", "Gp IPCA"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","","Índice Geral",Replacer.ReplaceValue,{"Gp IPCA"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

