table municipios
	lineageTag: 6b9f47b7-1fe0-4885-bd5f-c96b47d617a5

	column codigo_ibge
		dataType: int64
		formatString: 0
		lineageTag: cadb4cee-e893-4231-a50c-8f066154efbe
		summarizeBy: none
		sourceColumn: codigo_ibge

		annotation SummarizationSetBy = Automatic

	column nome
		dataType: string
		lineageTag: e91f47bb-c4ba-4da8-ba22-13a6688d94cb
		summarizeBy: none
		sourceColumn: nome

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		formatString: 0
		lineageTag: 5bfd9de6-c318-4a0f-9d2f-a24dc89678b7
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: latitude

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		formatString: 0
		lineageTag: f40256d8-1781-4ebe-b5b1-03941592e5e1
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: longitude

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column capital
		dataType: int64
		formatString: 0
		lineageTag: a1b487fc-fd05-4396-b984-ad03c5416338
		summarizeBy: none
		sourceColumn: capital

		annotation SummarizationSetBy = Automatic

	column codigo_uf
		dataType: int64
		formatString: 0
		lineageTag: 7431ef2e-1f08-4e3b-b4ab-5141e85030a5
		summarizeBy: none
		sourceColumn: codigo_uf

		annotation SummarizationSetBy = Automatic

	column siafi_id
		dataType: int64
		formatString: 0
		lineageTag: c785f942-9161-49e7-83c6-2b1956cbd6fe
		summarizeBy: none
		sourceColumn: siafi_id

		annotation SummarizationSetBy = Automatic

	column ddd
		dataType: int64
		formatString: 0
		lineageTag: c408c405-fc3f-4909-a72d-f4949a421536
		summarizeBy: none
		sourceColumn: ddd

		annotation SummarizationSetBy = Automatic

	column fuso_horario
		dataType: string
		lineageTag: 4d533570-188f-4825-b267-6cc2a0fe7eb8
		summarizeBy: none
		sourceColumn: fuso_horario

		annotation SummarizationSetBy = Automatic

	column pais = "Brasil"
		lineageTag: 4672d530-be6a-49a3-b0b5-d718c761604b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition municipios = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Applications\App Files\Microsoft\Power BI\municipios.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"codigo_ibge", Int64.Type}, {"nome", type text}, {"latitude", Int64.Type}, {"longitude", Int64.Type}, {"capital", Int64.Type}, {"codigo_uf", Int64.Type}, {"siafi_id", Int64.Type}, {"ddd", Int64.Type}, {"fuso_horario", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

